// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7apg4FWXqK_LyAIe88uM_UGTqble4Pg',
    appId: '1:937702073916:web:65636a74b1cc77f8ea8539',
    messagingSenderId: '937702073916',
    projectId: 'starlight-c576f',
    authDomain: 'starlight-c576f.firebaseapp.com',
    databaseURL: 'https://starlight-c576f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlight-c576f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-fPWYtgZKlaZZr1f_ONr68no4jvfyms',
    appId: '1:937702073916:android:aed47b94ab0c9c6aea8539',
    messagingSenderId: '937702073916',
    projectId: 'starlight-c576f',
    databaseURL: 'https://starlight-c576f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlight-c576f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUOQCj75tQpb3yZ-emEMlKUFkh27Lap60',
    appId: '1:937702073916:ios:847895fc5e33e38eea8539',
    messagingSenderId: '937702073916',
    projectId: 'starlight-c576f',
    databaseURL: 'https://starlight-c576f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlight-c576f.appspot.com',
    iosBundleId: 'com.example.starlight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUOQCj75tQpb3yZ-emEMlKUFkh27Lap60',
    appId: '1:937702073916:ios:847895fc5e33e38eea8539',
    messagingSenderId: '937702073916',
    projectId: 'starlight-c576f',
    databaseURL: 'https://starlight-c576f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlight-c576f.appspot.com',
    iosBundleId: 'com.example.starlight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7apg4FWXqK_LyAIe88uM_UGTqble4Pg',
    appId: '1:937702073916:web:73e95b8d9ce9c915ea8539',
    messagingSenderId: '937702073916',
    projectId: 'starlight-c576f',
    authDomain: 'starlight-c576f.firebaseapp.com',
    databaseURL: 'https://starlight-c576f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlight-c576f.appspot.com',
  );
}
